#!/bin/bash


. `dirname $0`/mvn_functions

cd $1

rel=$(to_release $curr)
dev=$(next_snapshot $rel)

echo "$curr - $rel - $dev"

git add . && git commit -m "[ci-skip] release prepare $rel" && git push

mvn --batch-mode versions:set -DnewVersion=$rel
git tag -a $rel -m "[ci-skip] release $rel" && git push origin $rel


mvn deploy 

mvn --batch-mode versions:set -DnewVersion=$dev
git add . && git commit -m "[ci-skip] release finish" && git push

